# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fitdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('steps', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('fat', models.IntegerField()),
            ],
        ),
    ]
